sudo: required
language: java

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

#os:
#  - linux
#  - osx
#
#matrix:
#  allow_failures:
#    - os: osx
